version: '3.7'
services:
  minecode:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: minecode
    hostname: minecode
    env_file: .env
    volumes:
      - ./:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/.next
    ports:
      - 3000:3000
