on: 
  milestone:
    types: [closed]
name: milestoneClosure
jobs:
  openPR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        branch: master
